### ISSUE TITLE
😯学习了～

### ISSUE THREAD

**Issue by olOwOlo** [NickYadance/jiliguala-newbie#1]
`:as :json` 可以直接转换

https://github.com/NickYadance/jiliguala-newbie/blob/ef2f1490b38918d12c8b9b13884df22338f62a5c/src/newbie/service/weixin_service.clj#L20-L26

---

这个..会抛异常吧

https://github.com/NickYadance/jiliguala-newbie/blob/ef2f1490b38918d12c8b9b13884df22338f62a5c/src/newbie/service/weixin_service.clj#L34

---

这个东西有 [tolitius/cprop](https://github.com/tolitius/cprop) 和 [tolitius/mount](https://github.com/tolitius/mount) 这种搭配 —— [luminus-template](https://github.com/luminus-framework/luminus-template)

https://github.com/NickYadance/jiliguala-newbie/blob/ef2f1490b38918d12c8b9b13884df22338f62a5c/src/newbie/repository/mongodb.clj#L10-L18

**Comment by NickYadance** [comment]
done
